# Mandatory settings

name: aksels.io
paginate: 25
paginate_path: "/posts/page/:num/"
url: http://aksels.io/
blog_theme: light

# Optional settings

discus_identifier: aksels
ga_analytics: UA-88694407-1
rss_enabled: false
social:
  dribbble: # Add your Dribbble handle
  facebook: # Add your Facebook handle
  flickr: aksels
  github: AkselsLedins
  linkedin: akselsledins
  twitter: AkselsLedins
  email: aksels.ledins@gmail.com
  bitcoin: # Add your Bitcoin link or address

# Important settings (change at own risk)

assets:
  compress:
    css: true
    js: true
  features:
    automatic_img_size: false
  sources:
    - _assets/bower
    - _assets/fonts
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - _vendor/
collections:
  my_tags:
    output: true
    permalink: /tag/:slug/
defaults:
  -
    scope:
      path: ""
      type: my_tags
    values:
      layout: articles_by_tag
exclude:
  - .bowerrc
  - .travis.yml
  - bin/*
  - bower.json
  - circle.yml
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor/
gems:
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
permalink: posts/:slug
